### ISSUE TITLE
"Failed awaiting on state barrier"

### ISSUE THREAD

**Issue by buro9** [stealthly/go_kafka_client#139]
Related to PR #127 and https://github.com/stealthly/go_kafka_client/commit/5b92ab37c8e3d2588c37ae671679fc78a4e5a6d8

We're seeing our staging environment produce the following log lines 3 minutes after startup:

```
2015-07-20/18:57:13 [ERROR] [zk] Failed awaiting on state barrier 705508e0b7ca3fc982c5f75af1d557bb [Timedout waiting for consensus on barrier path /consumers/scancheckgroup/api/rebalance/705508e0b7ca3fc982c5f75af1d557bb]
2015-07-20/18:57:43 [ERROR] [zk] Failed awaiting on state barrier 2ef6195d0b05c12077b7e7f12cf2b387 [Timedout waiting for consensus on barrier path /consumers/scancheckgroup/api/rebalance/2ef6195d0b05c12077b7e7f12cf2b387]
2015-07-20/18:57:54 [ERROR] [zk] Failed awaiting on state barrier 507988448b8ba0e9bb84ea28650fcaba [Timedout waiting for consensus on barrier path /consumers/scancheckgroup/api/rebalance/507988448b8ba0e9bb84ea28650fcaba]
2015-07-20/18:58:20 [ERROR] [zk] Failed awaiting on state barrier 01ec42775cf5701877fd78db18e05c90 [Timedout waiting for consensus on barrier path /consumers/scancheckgroup/api/rebalance/01ec42775cf5701877fd78db18e05c90]
2015-07-20/18:58:20 [ERROR] [zk] Failed awaiting on state barrier 01ec42775cf5701877fd78db18e05c90 [Timedout waiting for consensus on barrier path /consumers/scancheckgroup/api/rebalance/01ec42775cf5701877fd78db18e05c90]
2015-07-20/18:58:20 [ERROR] [zk] Failed awaiting on state barrier 01ec42775cf5701877fd78db18e05c90 [Timedout waiting for consensus on barrier path /consumers/scancheckgroup/api/rebalance/01ec42775cf5701877fd78db18e05c90]
2015-07-20/18:58:20 [ERROR] [zk] Failed awaiting on state barrier 01ec42775cf5701877fd78db18e05c90 [Timedout waiting for consensus on barrier path /consumers/scancheckgroup/api/rebalance/01ec42775cf5701877fd78db18e05c90]
2015-07-20/18:58:20 [ERROR] [zk] Failed awaiting on state barrier 01ec42775cf5701877fd78db18e05c90 [Timedout waiting for consensus on barrier path /consumers/scancheckgroup/api/rebalance/01ec42775cf5701877fd78db18e05c90]
2015-07-20/18:58:20 [ERROR] [zk] Failed awaiting on state barrier 01ec42775cf5701877fd78db18e05c90 [Timedout waiting for consensus on barrier path /consumers/scancheckgroup/api/rebalance/01ec42775cf5701877fd78db18e05c90]
2015-07-20/18:58:20 [ERROR] [zk] Failed awaiting on state barrier 01ec42775cf5701877fd78db18e05c90 [Timedout waiting for consensus on barrier path /consumers/scancheckgroup/api/rebalance/01ec42775cf5701877fd78db18e05c90]
2015-07-20/18:58:20 [ERROR] [zk] Failed awaiting on state barrier 01ec42775cf5701877fd78db18e05c90 [Timedout waiting for consensus on barrier path /consumers/scancheckgroup/api/rebalance/01ec42775cf5701877fd78db18e05c90]
panic: Could not reach consensus on state barrier.

goroutine 35 [running]:
github.com/stealthly/go_kafka_client.func·013()
    /home/user/src/github.com/stealthly/go_kafka_client/consumer.go:650 +0xb8d
github.com/stealthly/go_kafka_client.inLock(0xc2088305a8, 0xc2083d3f08)
	/home/user/src/github.com/stealthly/go_kafka_client/utils.go:44 +0x51
github.com/stealthly/go_kafka_client.(*Consumer).rebalance(0xc208830580)
	/home/user/src/github.com/stealthly/go_kafka_client/consumer.go:671 +0x73
github.com/stealthly/go_kafka_client.(*Consumer).reinitializeConsumer(0xc208830580)
	/home/user/src/github.com/stealthly/go_kafka_client/consumer.go:295 +0x4e
github.com/stealthly/go_kafka_client.(*Consumer).createMessageStreams(0xc208830580, 0xc2083cd470)
	/home/user/src/github.com/stealthly/go_kafka_client/consumer.go:270 +0x159
created by github.com/stealthly/go_kafka_client.(*Consumer).StartStatic
	/home/user/src//github.com/stealthly/go_kafka_client/consumer.go:112 +0x3c
```

This happens every time we start the client on that environment... which means we're guessing it's something to do with config within that environment (we're not seeing it in our development environment).

@marcusking01 or others, what information could help us work out the root cause? Or where should we look?

**Comment by serejja** [comment]
Hi @buro9 can you please post your consumer configs for this and dev environments so we can determine what configs differ? Are they even different? Thanks

**Comment by buro9** [comment]
Sure, we have basically implemented this lib as per https://github.com/stealthly/go_kafka_client/tree/master/consumers

Our properties file is this:

```
#Consumer identity
client_id=scancheck
group_id=scancheckgroup
num_consumers=1
topic=scancheck
log_level=warn

#Zookeeper connection settings
zookeeper_connect=:2181
zookeeper_timeout=1s

#workers settings
num_workers=1
max_worker_retries=3
worker_backoff=500ms
worker_retry_threshold=100
worker_considered_failed_time_window=500ms
worker_batch_timeout=5m
worker_task_timeout=1m
worker_managers_stop_timeout=1m

#Rebalance settings
rebalance_barrier_timeout=30s
rebalance_max_retries=4
rebalance_backoff=5s
partition_assignment_strategy=range
exclude_internal_topics=true

#Fetcher settings
num_consumer_fetchers=1
fetch_batch_size=100
fetch_message_max_bytes=5242880
fetch_min_bytes=1
fetch_batch_timeout=5s
requeue_ask_next_backoff=1s
fetch_wait_max_ms=100
socket_timeout=30s
queued_max_messages=3
refresh_leader_backoff=200ms
fetch_metadata_retries=3
fetch_metadata_backoff=500ms

#Offsets settings
offsets_storage=zookeeper
auto_offset_reset=smallest
offsets_commit_max_retries=5

#Deployment
deployment_timeout=0s

```

The only differences between this and our staging and prod are that staging and prod both have a dot in the topic name, and use multiple comma-delimited zookeeper servers in the connection:

```
topic=scan.check
zookeeper_connect={a long list of servers}
```

No other differences exist in the consumer config.

**Comment by marcusking01** [comment]
@buro9 We've seen similar issues.  Essentially what is happening is that all of the consumers in your pool are failing to agree on the same barrier id.  The problem we were seeing was that the hosts NEVER all agreed on the same barrier id and thus no one was consuming from kafka.  We introduced a 3 minute timeout to agree on a barrier id where we essentially panic (stopping the service) and rely on supervision to restart the service(s).  The hope is that by everyone going away and coming online at nearly the same time they will agree on a state barrier id.

**Comment by buro9** [comment]
A bit brute force, but thank you... that works for me. I'll work on getting our environment and ops to accept this as the standard working parameter for the consumer.

**Comment by marcusking01** [comment]
@buro9  
Agree it's a bit brute force.  Internally there have been a few minor fixes that seem to make things behave better.  We're testing them now and may release a PR when it gets the green light.  Friendly tip, at some point clear out the zk node /consumers/{your_consumer_name}/api/rebalance  I've found that over time the more build up of old barrier ids, the more of a problem rebalance becomes.

**Comment by prasincs** [comment]
@marcusking01 how are you panicking when the barrier times out? I don't see any place in the API where I can trigger that (a callback or something).. are you just doing that on a fork of `go_kafka_client` ?
